### PR TITLE
Merge into upstream

### PR DESCRIPTION
**Pull request by charmitro**
@DesmondSanctity @VinD22 Merge & resolve all conflicts.
This is the code from our fork, so make sure you test everything first.

### CODE REVIEW

**Comment by DesmondSanctity** [comment]
Okay will check it out

**Review by DesmondSanctity — COMMENTED** [review]
I have reviewed the merge conflicts and fixed

**Comment by charmitro** [comment]
There issues with branch https://github.com/CherryNetwork/apps/tree/feature/treasury-recurring-proposals after the merge. Please fix them.

**Review by DesmondSanctity — COMMENTED** [review]
Any hint in the issues or screenshot? @charmitro

**Comment by charmitro** [comment]
> Any hint on the issues or screenshot? @charmitro

Just run it and fix warnings.

**Review by DesmondSanctity — COMMENTED** [review]
merged

**Pull request merged**
